### ISSUE TITLE
Client analytics not working?

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2788]
We've actually seen a drop in our client analytics over the last few days even as downloads have gone up significantly. It seems like something's not working correctly.

You mind taking a look @atavism? I can give it a try too.

**Comment by atavism** [comment]
@myleshorton Yep, happy to take a look!

**Comment by myleshorton** [comment]
I went ahead and started looking at this, and it appears there are two issues:

1) The call from the Lantern UI uses "tid=development"
2) The call from the backend has no cid

So I think #1 is definitely not recorded, and #2 is probably not recorded. I can just take this one since I'm in the area if that's ok @atavism!

**Comment by atavism** [comment]
@myleshorton That's fine! Related to #1, I realized we still have some code in there related to the welcome screen we should remove (now that we're no longer presenting or checking for it). For #2, we're always including the cid parameter (with a default instance id)--why do you think its not being included?

**Comment by myleshorton** [comment]
> For #2, we're always including the cid parameter (with a default instance id)--why do you think its not being included?

I'm just logging the full request over the wire, which shows:

```
Jul 23 19:01:59.552 - 0m0s DEBUG analytics: analytics.go:149 Full analytics request: POST /collect HTTP/1.1
Jul 23 19:01:59.552 - 0m0s Host: ssl.google-analytics.com
Jul 23 19:01:59.552 - 0m0s User-Agent: Go 1.1 package http
Jul 23 19:01:59.552 - 0m0s Content-Length: 73
Jul 23 19:01:59.552 - 0m0s Content-Type: application/x-www-form-urlencoded
Jul 23 19:01:59.552 - 0m0s Accept-Encoding: gzip
Jul 23 19:01:59.552 - 0m0s
Jul 23 19:01:59.552 - 0m0s _v=j12&dh=localhost&sr=1440x900&t=pageview&tid=UA-21815217-2&ul=en-us&v=1
```

I'm actually not sure why that DefaultInstanceId doesn't seem to be getting included code-wise, but I also think it should probably be 555, but that likely doesn't matter. I'll keep fiddling..

**Comment by atavism** [comment]
@myleshorton Just opened https://github.com/getlantern/lantern/pull/2806 -- looks like there were a few things going on:

- We started passing in the lantern version as an event value, but apparently that value can only be an integer (that's not really documented anywhere, and it's confusing because it was working previously). I'm including it as a custom variable once again. I verified these are showing up in the dashboard with the test account you created.
- We had a check previously to make sure no analytics requests were sent unless the welcome screen was seen for the first time. As that's obviously no longer applicable, no new UI requests were being sent consequently. Should be fixed now.

**Comment by atavism** [comment]
Oh, per your suggestion, I switched the instance id to be 555 as well since that's the default anonymous client ID: https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide (though I don't think it makes a difference)

**Comment by myleshorton** [comment]
Nice! I just commented on the PR but do see those hits in analytics now. Still weird on that CID thing, but awesome the data's getting in there!

**Comment by myleshorton** [comment]
Unfortunately we're still not seeing any of these analytics events in our analytics. Not sure what's up.

**Comment by myleshorton** [comment]
I was able to get it working with a new ID -- maybe it's not liking our multiple uses of that ID or something. Trying the new one.

**Comment by myleshorton** [comment]
This was working for a second and then stopped. From https://groups.google.com/forum/#!topic/google-analytics-measurement-protocol/LN8WfJAPla8 it looks like we might have to generate custom client IDs for each client. Looking at this now.

**Comment by myleshorton** [comment]
Using this it looks like fixing this could be as simple as:

1. Auto-generating a new client ID (cid) for each lantern install
1. Using "dp" instead of "dh" arguments.

https://ga-dev-tools.appspot.com/hit-builder/

**Comment by myleshorton** [comment]
Although the above is different depending on where we're creating the hit from -- dp is required for pageviews but not events apparently.
