### ISSUE TITLE
Mobile - Some characters not appearing correctly, such as '

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#4018]

**Comment by myleshorton** [comment]
![image](https://cloud.githubusercontent.com/assets/1143966/14649495/2831522c-061c-11e6-86e4-b430fd3de6b2.png)

**Comment by atavism** [comment]
Seems like this should be taken care of by the feed server. Any reason we can't normalize article titles before generating the feed, @xiam?

**Comment by myleshorton** [comment]
@atavism was also mentioning one of the diffbot fields normalizes character encodings as well. Maybe we can use that @xiam or just make sure to normalize them ourselves?

**Comment by myleshorton** [comment]
Can we solve this on the server @xiam?

**Comment by xiam** [comment]
I'll add it to the server tasks, @myleshorton, @atavism

**Comment by xiam** [comment]
Think it's fixed now.

**Comment by myleshorton** [comment]
Nice so just add the QA label @xiam and assign it to @sunshine19090!

**Comment by myleshorton** [comment]
This one looking OK @sunshine19090?

**Comment by sunshine19090** [comment]
No, I still see the special characters. I will add the screenshot soon.

**Comment by sunshine19090** [comment]
![screenshot_2016-04-21-14-30-00](https://cloud.githubusercontent.com/assets/11394369/14725050/90fe436a-07ce-11e6-9396-9627aa0b2d58.png)
![screenshot_2016-04-21-14-29-41](https://cloud.githubusercontent.com/assets/11394369/14725051/91004930-07ce-11e6-8334-d40e90fb69c9.png)

**Comment by atavism** [comment]
Weird.. I'm not seeing that:

![image](https://cloud.githubusercontent.com/assets/6346213/14725152/24b575d8-07cf-11e6-87ad-f607a0efc081.png)
